#!/usr/bin/python

import random

temáticas = [
    "Horror",
    "Hambre",
    "Survival",
    "Crafting",
    "Medidor de HP",
    "Medidor de magia",
    "Combustible",
    "Viajes",
    "Minimalismo",
    "Electricidad",
    "Química",
    "Metal",
    "Pastel",
    "Plantas",
    "Flores",
    "Insectos",
    "Mariposas",
    "Abejas",
    "Árboles",
    "Carne",
    "Futuro",
    "Serpientes",
    "Cielo",
    "Memoria",
    "Pasado",
    "Tormenta",
    "Mar",
    "Adorable",
    "Criminales",
    "Ilusiones ópticas",
    "Libros",
    "Muerte",
    "Chatarra",
    "Chocolate",
    "Vainilla",
    "Asquerosidad",
    "Aluminio",
    "Religión",
    "Buitre",
    "Cosas peludas",
    "Furia",
    "Enfermedad",
    "Explosiones",
    "Alarma",
    "Rotación",
    "Atenazar",
    "Triada",
    "Dualidad",
    "Deshielo",
    "Esculturas",
    "Límite de tiempo",
    "Intelecto",
    "Inclinación",
    "Inmortalidad",
    "Boxeo",
    "Luz",
    "Sombra",
    "Dibujo",
    "Comida",
    "Gracioso",
    "Feliz",
    "Robots",
    "Veneno",
    "Plataformas",
    "Música",
    "Agua",
    "Guerra",
    "Fuego",
    "Aire",
    "Brujas",
    "Mounstruos",
    "Animales",
    "Volcanes",
    "Hielo",
    "Jungla",
    "Cavernas",
    "Transformación",
    "Tierra",
    "Terrorífico",
    "Satánico",
    "Diablos",
    "Colorido",
    "Ritmo",
    "Kawaii",
    "Enemigos gigantes",
    "Enemigos miniatura",
    "Plumas",
    "Mitología",
    "Acertijos",
    "Rompecabezas",
    "Armas de fuego",
    "Lásers",
    "Tecnología",
    "Cyberpunk",
    "Steampunk",
    "Powerups",
    "Objetos recolectables",
    "Bombas",
    "Cuchillos",
    "Medieval",
    "Arco",
    "Flechas",
    "Carreras",
    "Azar",
    "Dados",
    "Plataformas móviles",
    "Naves",
    "Aviones",
    "Tarjetas/Cartas",
    "Fantasmas",
    "Detectives",
    "Armas consumibles",
    "Hechizos",
    "Hentai",
    "Zonas desbloqueables",
    "Zombies",
    "Espacio exterior",
    "Relámpagos",
    "Parque",
    "Carbón",
    "Dientes",
    "Calaveras",
    "Alas",
    "Mover objetos",
    "Biología",
    "Truenos",
    "Lluvia",
    "Péndulos",
    "Azúcar",
    "Jinete",
    "Neptuno",
    "Perlas",
    "Peces",
    "Escamas",
    "Pulcritud",
    "Castillo",
    "Calabozo",
    "Calor",
    "Frío",
    "Industrial",
    "Fábrica",
    "Dispositivos",
    "Computadoras",
    "Cúspide",
    "Rascacielos",
    "Temperatura",
    "Soldados",
    "Esferas",
    "Cubos",
    "Pirámides",
    "Dulce",
    "Madera",
    "Joyas",
    "Gemas",
    "Relojería",
    "Engranes",
    "Corrientes marinas",
    "Bandas transportadoras",
    "Nivel vertical",
    "Lava",
    "barcos",
    "botones",
    "palancas",
    "Montañas",
]


botones = [
    "1",
    "2",
    "2",
    "3",
    "3",
    "4",
    "4",
    "4",
    "4",
    "5",
    "5",
    "5",
    "5",
    "6",
    "6",
    "6",
    "6",
    "6",
    "Sin límite",
    "Sin límite",
    "Sin límite",
    "Sin límite",
    "Sin límite",
]
colores = [
    "Azul",
    "Rojo",
    "Verde",
    "Amarillo",
    "Cyan",
    "Morado",
    "Naranja",
    "Café",
    "Magenta",
]


limcolores = [
    "2",
    "4" "4",
    "4",
    "8",
    "8",
    "8",
    "8",
    "16",
    "16",
    "16",
    "16",
    "Sin Límite",
    "Sin límite",
]

plataformas = ["Android", "PC"]

temanum = random.randint(2, 5)
spritenum = random.randint(2, 3)
colornum = random.randint(2, 3)

print("\nTemáticas aleatorias:")

for i in range(0, temanum):
    print("\t• " + temáticas[random.randint(0, len(temáticas) - 1)])
print("Colores:")
for i in range(0, colornum):
    print("\t• " + colores[random.randint(0, len(colores) - 1)])

print("Botones usables:")
print("\t• " + botones[random.randint(0, len(botones) - 1)])
print("Límte de colores: ")
print("\t• " + limcolores[random.randint(0, len(limcolores) - 1)])
print("Plataforma: ")
print("\t• " + plataformas[random.randint(0, len(plataformas) - 1)])
print("Tiempo límite estimado: ")
print("\t• " + str(random.randint(4, 20)) + " días")

print("\n----------------------------------------")
print(" ")
